### PR TITLE
Fixed image that wasnt loading

### PR DESCRIPTION
**Pull request by hawktuahyuri**
it said access denied before
I assumed it was the autosave image

### CODE REVIEW

**Comment by Sapphiku** [comment]
static folder won't work though? 

it should just be /img/2024-02-23/chart-editor-crash-recovery.png or something like that

**Comment by hawktuahyuri** [comment]
look at the code tab, the img folder is under the static folder
I saw your pull request, it achieves pretty much the same thing, except mine is the relative directory and yours is the https:// directory

**Comment by Sapphiku** [comment]
ah got it 

I don't really know too much on how this stuff works - I tried putting it on the blog url but I end up with this
image

**Comment by hawktuahyuri** [comment]
yeah, the directory in github and the directory in the link are different. 'Tis weird

**Comment by Sapphiku** [comment]
try removing only the static directory?

**Comment by hawktuahyuri** [comment]
it works though. Go to preview mode

**Comment by ninjamuffin99** [comment]
closed in favour of #21 ! thank you both though!

**Pull request closed without merging**
